"""add_payment_transaction_ledger

Revision ID: 3e419f6477f1
Revises: f9c3d2a1b8e7
Create Date: 2026-05-23 00:16:49.772429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e419f6477f1'
down_revision = 'f9c3d2a1b8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'payment_transactions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('enrollment_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('course_id', sa.String(length=36), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('payment_method', sa.String(length=50), nullable=False),
        sa.Column('tx_code', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('processed_by', sa.String(length=36), nullable=True),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_payment_transactions_enrollment_id_enrollments'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_transactions_user_id_users')),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_payment_transactions_course_id_courses')),
        sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('fk_payment_transactions_processed_by_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transactions'))
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_processed_by'), ['processed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_tx_code'), ['tx_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_tx_code'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_processed_by'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_course_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_enrollment_id'))

    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
