"""add composite indexes for performance

Revision ID: 41db866ec8eb
Revises: a58f7747954d
Create Date: 2026-05-21 01:00:30.568304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41db866ec8eb'
down_revision = 'a58f7747954d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('idx_courses_status_deleted', ['status', 'is_deleted'], unique=False)

    with op.batch_alter_table('learning_logs', schema=None) as batch_op:
        batch_op.create_index('idx_learning_logs_user_action', ['user_id', 'action_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_learning_logs_user_action')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('idx_courses_status_deleted')

    # ### end Alembic commands ###
