"""add_cascade_deletes_and_update_schemas

Revision ID: 65d04a83a7e4
Revises: e7f4a6c2b901
Create Date: 2026-05-19 23:48:09.622393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d04a83a7e4'
down_revision = 'e7f4a6c2b901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_announcements_author_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_announcements_course_id_courses'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_announcements_author_id_users'), 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_announcements_course_id_courses'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_assignments_course_id_courses'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_assignments_course_id_courses'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_certificates_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_certificates_course_id_courses'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_certificates_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_certificates_course_id_courses'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_choices_question_id_questions'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_choices_question_id_questions'), 'questions', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_enrollments_course_id_courses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_enrollments_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_enrollments_course_id_courses'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_enrollments_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('forum_replies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_forum_replies_thread_id_forum_threads'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_forum_replies_author_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_forum_replies_thread_id_forum_threads'), 'forum_threads', ['thread_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_forum_replies_author_id_users'), 'users', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_forum_threads_course_id_courses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_forum_threads_author_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_forum_threads_author_id_users'), 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_forum_threads_course_id_courses'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('learning_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_learning_logs_lesson_id_lessons'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_learning_logs_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_learning_logs_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_learning_logs_lesson_id_lessons'), 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lessons_course_id_courses'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_lessons_course_id_courses'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_questions_quiz_id_quizzes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_questions_quiz_id_quizzes'), 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_answer', sa.Text(), nullable=True))
        batch_op.alter_column('choice_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_quiz_answers_question_id_questions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_quiz_answers_attempt_id_quiz_attempts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_quiz_answers_choice_id_choices'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quiz_answers_question_id_questions'), 'questions', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_quiz_answers_attempt_id_quiz_attempts'), 'quiz_attempts', ['attempt_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_quiz_answers_choice_id_choices'), 'choices', ['choice_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_quiz_attempts_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_quiz_attempts_quiz_id_quizzes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quiz_attempts_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_quizzes_course_id_courses'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quizzes_course_id_courses'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_submissions_user_assignment', ['user_id', 'assignment_id'])
        batch_op.drop_constraint(batch_op.f('fk_submissions_assignment_id_assignments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_submissions_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_submissions_graded_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_submissions_graded_by_users'), 'users', ['graded_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_submissions_assignment_id_assignments'), 'assignments', ['assignment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_submissions_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_submissions_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_submissions_assignment_id_assignments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_submissions_graded_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_submissions_graded_by_users'), 'users', ['graded_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_submissions_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_submissions_assignment_id_assignments'), 'assignments', ['assignment_id'], ['id'])
        batch_op.drop_constraint('uq_submissions_user_assignment', type_='unique')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_quizzes_course_id_courses'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quizzes_course_id_courses'), 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_quiz_attempts_quiz_id_quizzes'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_quiz_attempts_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quiz_attempts_quiz_id_quizzes'), 'quizzes', ['quiz_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_quiz_attempts_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_quiz_answers_choice_id_choices'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_quiz_answers_attempt_id_quiz_attempts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_quiz_answers_question_id_questions'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quiz_answers_choice_id_choices'), 'choices', ['choice_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_quiz_answers_attempt_id_quiz_attempts'), 'quiz_attempts', ['attempt_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_quiz_answers_question_id_questions'), 'questions', ['question_id'], ['id'])
        batch_op.alter_column('choice_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('text_answer')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_questions_quiz_id_quizzes'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_questions_quiz_id_quizzes'), 'quizzes', ['quiz_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notifications_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notifications_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lessons_course_id_courses'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_lessons_course_id_courses'), 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('learning_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_learning_logs_lesson_id_lessons'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_learning_logs_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_learning_logs_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_learning_logs_lesson_id_lessons'), 'lessons', ['lesson_id'], ['id'])

    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_forum_threads_course_id_courses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_forum_threads_author_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_forum_threads_author_id_users'), 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_forum_threads_course_id_courses'), 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('forum_replies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_forum_replies_author_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_forum_replies_thread_id_forum_threads'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_forum_replies_author_id_users'), 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_forum_replies_thread_id_forum_threads'), 'forum_threads', ['thread_id'], ['id'])

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_enrollments_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_enrollments_course_id_courses'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_enrollments_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_enrollments_course_id_courses'), 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_choices_question_id_questions'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_choices_question_id_questions'), 'questions', ['question_id'], ['id'])

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_certificates_course_id_courses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_certificates_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_certificates_course_id_courses'), 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_certificates_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_assignments_course_id_courses'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_assignments_course_id_courses'), 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_announcements_course_id_courses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_announcements_author_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_announcements_course_id_courses'), 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_announcements_author_id_users'), 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###
