"""add completed_at, graded_at, graded_by columns

Revision ID: b2154fb1a5b7
Revises: 
Create Date: 2026-05-11 17:32:34.273801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2154fb1a5b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('graded_by', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_submissions_graded_by_users'), 'users', ['graded_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_submissions_graded_by_users'), type_='foreignkey')
        batch_op.drop_column('graded_by')
        batch_op.drop_column('graded_at')

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
